### ISSUE TITLE
iphone browsers leftborder to close to edge of screen

### ISSUE THREAD

**Issue by pokespeon** [CodeForNC/nc-reentry-resources-content#12]
needs more space

**Comment by ejaxon** [comment]
@pokespeon Was this on the new site that was running at the event or the [old one](http://www.buncombereentryhub.org/)? If the latter, I'll just close since we're doing a full re-design. If the new site, I'd like to move this issue over to the [public site repository](https://github.com/CodeForNC/reentry-resources-hub).

**Comment by ChrisTheDBA** [comment]
It was the one at the existing site at the event

**Comment by ejaxon** [comment]
This should be addressed in the new site.
